[versions]
coroutinesReactor = "1.10.2"
kotest = "6.0.5"
kotlin = "2.2.21"
reactor = "3.8.0"
ktor = "3.3.2"

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
viaduct-application = { id = "com.airbnb.viaduct.application-gradle-plugin", version.ref = "viaduct" }
viaduct-module = { id = "com.airbnb.viaduct.module-gradle-plugin", version.ref = "viaduct" }

[libraries]
# Viaduct
viaduct-bom = { group = "com.airbnb.viaduct", name = "bom", version.ref = "viaduct" }
viaduct-api = { group = "com.airbnb.viaduct", name = "api", version.ref = "viaduct" }
viaduct-runtime = { group = "com.airbnb.viaduct", name = "runtime", version.ref = "viaduct" }
viaduct-test-fixtures = { group = "com.airbnb.viaduct", name = "test-fixtures", version.ref = "viaduct" }

# Common libraries
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "coroutinesReactor" }
reactor-core = { group = "io.projectreactor", name = "reactor-core", version.ref = "reactor" }

# Ktor-specific libraries
ktor-server-core-jvm = { group = "io.ktor", name = "ktor-server-core-jvm" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core" }
ktor-server-jetty = { group = "io.ktor", name = "ktor-server-jetty" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-config-yaml = { group = "io.ktor", name = "ktor-server-config-yaml" }
ktor-serialization-jackson = { group = "io.ktor", name = "ktor-serialization-jackson", version.ref = "ktor" }

# Testing
ktor-server-test-host = { group = "io.ktor", name = "ktor-server-test-host" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
kotest-runner-junit = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { group = "io.kotest", name = "kotest-assertions-json", version.ref = "kotest" }
